// <auto-generated />
using System;
using Famlyr.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Famlyr.Infrastructure.Migrations
{
    [DbContext(typeof(FamlyrDbContext))]
    [Migration("20251227232227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Famlyr.Core.Entities.FamilyTree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FamilyTrees");
                });

            modelBuilder.Entity("Famlyr.Core.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FamilyTreeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyTreeId")
                        .HasDatabaseName("IX_Persons_FamilyTreeId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Famlyr.Core.Entities.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RelativeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RelativeId")
                        .HasDatabaseName("IX_Relationships_RelativeId");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_Relationships_SubjectId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("Famlyr.Core.Entities.Person", b =>
                {
                    b.HasOne("Famlyr.Core.Entities.FamilyTree", "FamilyTree")
                        .WithMany("Persons")
                        .HasForeignKey("FamilyTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyTree");
                });

            modelBuilder.Entity("Famlyr.Core.Entities.Relationship", b =>
                {
                    b.HasOne("Famlyr.Core.Entities.Person", "Relative")
                        .WithMany("RelationshipsAsRelative")
                        .HasForeignKey("RelativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Famlyr.Core.Entities.Person", "Subject")
                        .WithMany("RelationshipsAsSubject")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relative");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Famlyr.Core.Entities.FamilyTree", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Famlyr.Core.Entities.Person", b =>
                {
                    b.Navigation("RelationshipsAsRelative");

                    b.Navigation("RelationshipsAsSubject");
                });
#pragma warning restore 612, 618
        }
    }
}
